name: Апдейт FuckWhiteLists
on:
  schedule:
    - cron: '0 */3 * * *' # Запуск раз в 3 часа
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  run-parser:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Разрешение на пуш результатов
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests urllib3

      - name: Run Parser
        run: python parser.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автоматическое обновление конфигов"
